### ISSUE TITLE
Client doesn't notify backend of disconnection on tab/window close

### ISSUE THREAD

**Issue by Lakshya2610** [grey-software/toonin#100]
bug after #97

**Comment by alir128** [comment]
I think on the extension we should monitor the peer rtc connection state instead of doing this over socket requests it would be more reliable.

**Comment by Lakshya2610** [comment]
> I think on the extension we should monitor the peer rtc connection state instead of doing this over socket requests it would be more reliable.

That's what I was thinking as well. Doing this over sockets seems unnecessary
