### ISSUE TITLE
Extension displays the old sharing state after closing the room

### ISSUE THREAD

**Issue by Lakshya2610** [grey-software/toonin#101]
bug after #98

**Comment by alir128** [comment]
Bug still exists can't stop sharing.

**Comment by Lakshya2610** [comment]
Not sure why that's happening, I tested it right now and it works fine. Can you give me more details/steps to reproduce the issue

**Comment by alir128** [comment]
Nvm, just tested the zip from master its all good.

**Comment by Lakshya2610** [comment]
@alir128 I think something's up with extension code from your branch, because that build also gave me the issue. Did you merge master into your issue100 branch?
