### ISSUE TITLE
Chrome extension should start sharing room when enter is pressed

### ISSUE THREAD

**Issue by ArsalaBangash** [grey-software/toonin#131]
I've observed users type the room name in and press enter thinking it would start sharing.

**Comment by alir128** [comment]
We can have the same functionality on the web app after typing in the Room Key and hitting enter it does the connection process.

**Comment by ArsalaBangash** [comment]
Thanks for the suggestion. Working on a PR right now!

**Comment by Lakshya2610** [comment]
Also, the text field for entering room key on the web-app should come into focus on page load. We had that in last version of the web-app (along with enter key functionality), but it got lost in the last major overhaul
