### ISSUE TITLE
Make Toonin extension compatible on Firefox.

### ISSUE THREAD

**Issue by alir128** [grey-software/toonin#15]
https://extensionworkshop.com/documentation/develop/porting-a-google-chrome-extension/

**Comment by alir128** [comment]
https://www.extensiontest.com/test/9b4165c0-18d0-11ea-b696-cb9fd93578b9

**Comment by ArsalaBangash** [comment]
Closing this issue since we're moving away from the extension model to a web app + get userDisplayMedia model.
