### ISSUE TITLE
Address generic object injection anti-pattern

### ISSUE THREAD

**Issue by ArsalaBangash** [grey-software/toonin#151]
extension/src/js/background/index.js
The peers object can be replaced with a class

client/src/host.js
The _this.peers object can be replaced with a class

backend/NetworkTree.js
I'm not exactly sure what to do about these atm 
![image](https://user-images.githubusercontent.com/19757203/72012373-a7753a80-327d-11ea-8950-61dd28b379c7.png)

**Comment by Lakshya2610** [comment]
This was fixed a while back. Most of the issues are gone now
