### ISSUE TITLE
report peer count back to host when using distributed streaming.

### ISSUE THREAD

**Issue by alir128** [grey-software/toonin#172]
Currently only peers connected to the root node are reported as the grand children only report to their respective parent nodes.

**Comment by Lakshya2610** [comment]
I think a simple increment/decrement signal would do the job. 

- Whenever a new node would join the network, it would send an increment signal to its parent. 
   This would bubble all the way to the root which should then change the counter value.

Decrement would work the same way.

**Comment by Lakshya2610** [comment]
Same issue already exists #143 . I'm closing that one and keeping this up
