### ISSUE TITLE
Have share audio checked by default 

### ISSUE THREAD

**Issue by ArsalaBangash** [grey-software/toonin#178]
By default, the Share Audio option on the Share Your Screen modal is unchecked. 

![image](https://user-images.githubusercontent.com/19757203/80285007-1c1a9a80-86f0-11ea-8112-c73831002416.png)

Having it checked fits our use case more. I don't envision many users  __by default__ choosing to only share video without the audio.

**Comment by alir128** [comment]
This is not possible anymore https://chromium.googlesource.com/chromium/src.git/+/a97583c9b4117f3bb559b218f6eb2ae065dd5fe8

**Comment by ArsalaBangash** [comment]
Let's add an image prompt to make sure users understand this. 

We should notify users if the audio option is checked https://github.com/grey-software/toonin/issues/180
