### ISSUE TITLE
Nodes reconnecting due to fallen hosts don't connect properly to the new node

### ISSUE THREAD

**Issue by Lakshya2610** [grey-software/toonin#195]
This worked fine in the last iteration of the web app with Vuetify. Switching to Quasar broke the functionality. I have noticed 2 issues:

- If the connection is established, the video player doesn't reopen
- The connection fails

(Note: It could be that the connection fails in the first case as well. This needs to be looked into more to pinpoint the exact problem)

**Comment by alir128** [comment]
The logoff message is not being sent when a client closes the tab. Because of that the network tree doesn't update. This is also causes peer count to not be updated for root node.

**Comment by alir128** [comment]
`socket.on("disconnect", () => {
    console.log("user disconnected " + socket.id);
  });`

We should somehow use this event to figure out which room a socket belonged in.
