### ISSUE TITLE
Warning on loading extension on chrome

### ISSUE THREAD

**Issue by Lakshya2610** [grey-software/toonin#29]
A cookie associated with a cross-site resource at http://www.toonin.ml/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Comment by ArsalaBangash** [comment]
Archiving this issue since we're moving away from the extension.
