### ISSUE TITLE
Extension's CSS is messing up all the webpages even when not using it

### ISSUE THREAD

**Issue by Lakshya2610** [grey-software/toonin#33]

**Comment by luu-alex** [comment]
This was caused by our inject.js, its fixed

**Comment by Lakshya2610** [comment]
In the latest build, there are a lot of elements in our extension. And because of mixing of  css properties, some elements in the extension become in-accessible on certain webpages depending on what CSS they are using. In short: Extension's CSS messes up the web-pages and Web-pages' CSS messes up the extension visuals

**Comment by Lakshya2610** [comment]
https://medium.com/@liviazhang/chrome-extension-how-to-completely-separate-your-content-scripts-css-from-websites-css-f379482be91a 

This might be useful
