### ISSUE TITLE
delete toonin room ids after 1-2 hours on server side.

### ISSUE THREAD

**Issue by alir128** [grey-software/toonin#41]

**Comment by Lakshya2610** [comment]
Instead of deleting rooms after certain time, maybe add a delete event on close tab?

**Comment by alir128** [comment]
yea thats possible too if you check the new code I have the event listener already setup for tab close that deletes the background data maybe we can do a socket emit call also to delete that id on the server.

**Comment by Lakshya2610** [comment]
That's great. I'll work on it. I'm almost done with the toggle mute/unmute feature

**Comment by Lakshya2610** [comment]
This issue has been fixed in pr #51
