### ISSUE TITLE
Tuning in via routes doesn't work on production

### ISSUE THREAD

**Issue by ArsalaBangash** [grey-software/toonin#64]
The web app currently does not tune in via routes such as **/roomName**

This is because the app is served statically. 

We may have to investigate to see if wrapping our Vue web app with a SSR framework like Nuxt would solve this for us.

**Comment by Lakshya2610** [comment]
The vue app can parse the roomID from the URL. So all we need to do is serve the Vue app on any URL matching www.toonin.ml/:roomID without changing the url. If we can do this, the app should handle the rest.

![image](https://user-images.githubusercontent.com/46510358/67906651-b89e1e80-fb4b-11e9-8b0c-88e0e834542f.png)

**Comment by alir128** [comment]
@ArsalaBangash is it okay if I take over this issue?

**Comment by alir128** [comment]
#92 will address this issue once vue router with dynamic routing is setup.
