### ISSUE TITLE
Create a separate file for all the global variables on the extension

### ISSUE THREAD

**Issue by Lakshya2610** [grey-software/toonin#76]
Code looks messy right now. One of the main reasons is because we have global variables scattered all over the code, especially in the background.js file

**Comment by alir128** [comment]
Ill take care of cleaning up the extension background.js code. I am thinking of splitting it based on client and host code because the file has gotten too big. The socket listeners can be put in a separate file.

**Comment by alir128** [comment]
I will wait for Alex's UI code to be merged on to master first before I refactor the background file.

**Comment by Lakshya2610** [comment]
Closing since we are moving away from the extension
