### ISSUE TITLE
Extension shows the starting page when reopened after starting a stream

### ISSUE THREAD

**Issue by Lakshya2610** [grey-software/toonin#88]
This bug happens randomly, not sure what's the exact cause is. My guess is that it's due to some state management issues. I've noticed that the extension throws this error pretty often

![image](https://user-images.githubusercontent.com/46510358/69126063-47c89300-0a75-11ea-9fde-7847eb7d1a58.png)

**Comment by alir128** [comment]
This bug happens when we try to run the extension from a previously opened tab on chrome after installing the extension. Its to do with how Chrome works with extension they dont get loaded onto already opened tabs. Maybe this is only an issue with Developer mode extensions?

**Comment by ArsalaBangash** [comment]
We could test to see why and when it happens.

**Comment by Lakshya2610** [comment]
> This bug happens when we try to run the extension from a previously opened tab on chrome after installing the extension. Its to do with how Chrome works with extension they dont get loaded onto already opened tabs. Maybe this is only an issue with Developer mode extensions?

I'll test this thoery out

**Comment by Lakshya2610** [comment]
> > This bug happens when we try to run the extension from a previously opened tab on chrome after installing the extension. Its to do with how Chrome works with extension they dont get loaded onto already opened tabs. Maybe this is only an issue with Developer mode extensions?
> 
> I'll test this thoery out

So I tested this. I loaded the extension yesterday and haven't reloaded it since. But it still happens every time.

**Comment by Lakshya2610** [comment]
This is irrelevant now
