### ISSUE TITLE
Audio Streaming through data channels has a clicking sound in the background

### ISSUE THREAD

**Issue by Lakshya2610** [grey-software/toonin#9]
When streaming audio through data channels, there is a clicking sound that can be heard on the client along with the audio. Between multiple data packets of audio, the audio wave is cut abruptly at a point other than the natural zero crossing leading to a "click" sound. 

Refer: http://alemangui.github.io/blog//2015/12/26/ramp-to-value.html

**Comment by alir128** [comment]
Hey, can close this issue?
